name: Create Mac Installer
on:
  push:
    tags:
      - v*

# For Code Signing please make sure the following secrets are defined in the repository:
# WINDOWS_CERTIFICATE_BASE64 - The Windows code signing certificate, base64 encoded
# WINDOWS_CERTIFICATE_PASSWORD - The password for Windows the certificate

jobs:
  mac:
    name: Create the Mac OS Installation
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Set backend environment
        working-directory: backend
        run: |
          pip install --upgrade setuptools pip wheel
          pip install t2wml-api
          pip install -r requirements.txt
          pip install pyinstaller semver
          pip uninstall -y typing typing-extensions
      - name: Compile Code
        working-directory: backend
        env:
          CI: false   # Otherwise React stops on warnings
          CSC_IDENTITY_AUTO_DISCOVERY: true
        run: |
          python packaging/prepare_installation.py --skip-electron-build --version ${{ github.ref }}
      - name: Build electron package
        uses: samuelmeuli/action-electron-builder@v1
        env:
          APPLE_ID: ${{secrets.APPLE_ID}}
          APPLE_ID_PASSWORD: ${{secrets.APPLE_ID_PASSWORD}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_root: electron
          build_script_name: build:mac
          mac_certs: ${{secrets.MAC_CERTIFICATE_BASE64}}
          mac_certs_password: ${{secrets.MAC_CERTIFICATE_PASSWORD}}
      - name: Rename installer to canonical name
        working-directory: electron/out
        run: |
          ls -l
          cp t2wml*.dmg t2wml.dmg

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload to Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: electron/out/t2wml.dmg
          asset_name: t2wml-${{ steps.get_version.outputs.VERSION }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
          body: "MacOS Installation Package"
