name: Create Standalone Executables
on:
  push:
    branches:
      - standalone
    tags:
      - 'v*'  # Version tags: v2.0

jobs:
  windows:
    name: Create Windows Executables
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Try Python OutputEncoding
        env:  # Replace unicode characters with ?
           PYTHONIOENCODING: :replace
           PYTHONLEGACYWINDOWSIOENCODING: true
        run: |
          cd $env:GITHUB_WORKSPACE/backend
          python try_print_utf8.py
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Build frontend
        env:
          CI: false   # Otherwise React stops on warnings
        run: |
          cd $env:GITHUB_WORKSPACE/frontend
          yarn install
          yarn build
      - name: Set backend environment
        run: |
          cd $env:GITHUB_WORKSPACE/backend
          pip install -r requirements.txt --extra-index-url https://pypi.fury.io/theresearchsoftwarecompany
          pip install pyinstaller pywin32
      - name: Create executable
        run: |
          cd $env:GITHUB_WORKSPACE/backend
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          python packaging/prepare_installation.py --version ${{ github.ref }}

