name: Create Standalone Executables
on:
  push:
    branches:
      - standalone
    tags:
      - 'v*'  # Version tags: v2.0

jobs:
  windows:
    name: Create Windows Executables
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Build frontend
        run: |
          cd $GITHUB_WORKSPACE/t2wml/frontend
          npm install
          npm run build
      - name: Build backend environment
        run: |
          cd $GITHUB_WORKSPACE/t2wml/backend
          pip install -r requirements.txt
          pip install pyinstaller pywin32
          python packaging/prepare_installation.py --version ${{ github.ref }}

