name: Create Linux Installation
on:
  push:
    tags:
      - v*

jobs:
  linux:
    name: Create the Linux Installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Set backend environment
        run: |
          cd $GITHUB_WORKSPACE/backend
          pip install --upgrade setuptools pip wheel
          pip install t2wml-api
          pip install -r requirements.txt
          pip install pyinstaller semver
          pip uninstall -y typing typing-extensions
      - name: Create executable
        env:
          CI: false   # Otherwise React stops on warnings
        run: |
          cd $GITHUB_WORKSPACE/backend
          python packaging/prepare_installation.py --version ${{ github.ref }}
      - name: Rename installer to canonical name
        run: |
          cd $GITHUB_WORKSPACE/electron/out
          cp t2wml*.AppImage t2wml.AppImage
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Upload to Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: electron/out/t2wml.AppImage
          asset_name: t2wml-${{ steps.get_version.outputs.VERSION }}.AppImage
          tag: ${{ github.ref }}
          overwrite: true
          body: "Linux Executable"

