name: Test Mac Signing
on:
  push:
    branches:
      - feature/code-signing

# For Code Signing please make sure the following secrets are defined in the repository:
# WINDOWS_CERTIFICATE_BASE64 - The Windows code signing certificate, base64 encoded
# WINDOWS_CERTIFICATE_PASSWORD - The password for Windows the certificate

jobs:
  mac:
    name: Create the Mac OS Installation
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Setup Code Signing Certificate
        shell: bash
        working-directory: electron
        env:
          KEYCHAIN_PASS: keychainpass
          CERTIFICATE_PASSWORD: "${{secrets.MAC_CERTIFICATE_PASSWORD}}"
          CERTIFICATE: "${{secrets.MAC_CERTIFICATE_BASE64"
        run: |
          echo $CERTIFICATE | base64 -d > certificate.p12
          security create-keychain -p $KEYCHAIN_PASS build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASS build.keychain
          security import certificate.p12 -k build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign

          security find-identity -v
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASS build.keychain

          security find-identity -v
      - name: Set backend environment
        working-directory: backend
        run: |
          pip install --upgrade setuptools pip
          pip install t2wml-api
          pip install -r requirements.txt
          pip install pyinstaller semver
      - name: Create executable
        working-directory: backend
        env:
          CI: false   # Otherwise React stops on warnings
          CSC_IDENTITY_AUTO_DISCOVERY: true
        run: |
          python packaging/prepare_installation.py --version 2.7.1-pre.5 # ${{ github.ref }}
      - name: Rename installer to canonical name
        working-directory: electron/out
        run: |
          ls -l
          cp t2wml*.pkg t2wml.pkg

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload to Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: electron/out/t2wml.pkg
          asset_name: t2wml-2.7.1-pre.5.pkg # ${{ steps.get_version.outputs.VERSION }}.pkg
          tag: 2.7.1-pre.5 # ${{ github.ref }}
          overwrite: true
          body: "MacOS Package"
