name: Test Mac Signing
on:
  push:
    branches:
      - feature/code-signing

# For Code Signing please make sure the following secrets are defined in the repository:
# WINDOWS_CERTIFICATE_BASE64 - The Windows code signing certificate, base64 encoded
# WINDOWS_CERTIFICATE_PASSWORD - The password for Windows the certificate

jobs:
  mac:
    name: Create the Mac OS Installation
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Extract Code Signing Certificate
        shell: bash
        working-directory: electron
        run: |
          echo "${{secrets.MAC_CERTIFICATE_BASE64}}" > certificate.pfx.base64
          cat certificate.pfx.base64 | base64 -d > certificate.pfx
      - name: Set backend environment
        run: |
          cd $GITHUB_WORKSPACE/backend
          pip install --upgrade setuptools pip
          pip install t2wml-api
          pip install -r requirements.txt
          pip install pyinstaller semver
      - name: Create executable
        env:
          CI: false   # Otherwise React stops on warnings
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          export CSC_LINK=$GITHUB_WORKSPACE/electron/certificate.pfx
          cd $GITHUB_WORKSPACE/backend
          python packaging/prepare_installation.py --version 2.7.1-pre.5 # ${{ github.ref }}
      - name: Rename installer to canonical name
        run: |
          cd $GITHUB_WORKSPACE/electron/out
          ls -l
          cp t2wml*.pkg t2wml.pkg

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload to Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: electron/out/t2wml.pkg
          asset_name: t2wml-2.7.1-pre.5.pkg # ${{ steps.get_version.outputs.VERSION }}.pkg
          tag: 2.7.1-pre.5 # ${{ github.ref }}
          overwrite: true
          body: "MacOS Package"
