name: Run Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Checkout t2wml-api
        run: git clone -b development https://github.com/usc-isi-i2/t2wml-api
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install ./t2wml-api
          pip install -r backend/requirements.txt
      - name: Run Tests
        run: |
          cd backend
          pytest tests     
       # This step should be enabled when SLACK_WEBHOOK_URL is added to the repo
      # - name: Report to Slack
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }} # optional
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: always() # Pick up events even if the job fails or is canceled.



